from interpreter import TokenType
keywords = {
    "and": TokenType.AND,
    "else": TokenType.ELSE,
    "false": TokenType.FALSE,
    "for": TokenType.FOR,
    "foreach": TokenType.FOR_EACH,
    "fn": TokenType.FUN,
    "cls": TokenType.CLASS,
    "if": TokenType.IF,
    "elif": TokenType.ELSE_IF,
    "nil": TokenType.NULL,
    "print": TokenType.PRINT,
    "println": TokenType.PRINTLN,
    "return": TokenType.RETURN,
    "break": TokenType.BREAK,
    "continue": TokenType.CONTINUE,
    "in": TokenType.IN,
    "true": TokenType.TRUE,
    "int": TokenType.TYPE_INTEGER,
    "str": TokenType.TYPE_STRING,
    "float": TokenType.TYPE_FLOAT,
    "bool": TokenType.TYPE_BOOLEN,
    "array": TokenType.TYPE_ARRAY,
    "while": TokenType.WHILE,
    "raise": TokenType.RAISE,
    "http": TokenType.HTTP,
    "ftp": TokenType.FTP,
    "stmp": TokenType.STMP,
    "tcp": TokenType.TCP,
    "ip": TokenType.IP,
    "ssl": TokenType.SSL,
}
