from interpreter import TokenType
keywords = {
    "and": TokenType.AND,
    "else": TokenType.ELSE,
    "false": TokenType.FALSE,
    "for": TokenType.FOR,
    "fn": TokenType.FUN,
    "if": TokenType.IF,
    "nil": TokenType.NULL,
    "print": TokenType.PRINT,
    "println": TokenType.PRINTLN,
    "return": TokenType.RETURN,
    "true": TokenType.TRUE,
    "int": TokenType.TYPE_INTEGER,
    "str": TokenType.TYPE_STRING,
    "float": TokenType.TYPE_FLOAT,
    "bool": TokenType.TYPE_BOOLEN,
    "while": TokenType.WHILE,
    "raise": TokenType.RAISE,
    "http": TokenType.HTTP,
    "ftp": TokenType.FTP,
    "stmp": TokenType.STMP,
    "tcp": TokenType.TCP,
    "ip": TokenType.IP,
    "ssl": TokenType.SSL,
}
